# Generated by Django 5.1.6 on 2025-03-05 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AboutMe',
            new_name='About',
        ),
    ]
